Add AssertionDependency
tgrapperon/swift-dependencies-additions pull request #28
Opened 2023-01-27 03:05 UTC by john-flanagan

Following up on our discussion [here](https://github.com/tgrapperon/swift-dependencies-additions/discussions/17) about creating an `assert` dependency.

2023-01-27 03:54 UTC, tgrapperon requested changes
Hey @john-flanagan! Thanks for the PR!
This is great! I was initially thinking about defining `assert` on top of `assertionFailure`, but it turns out that the [implementation](https://github.com/apple/swift/blob/2fc7659ed7874d069132add975df1178f36d0168/stdlib/public/core/Assert.swift#L40-L53) is very slightly different, so I guess it is better to keep them separated. We can maybe find a way to bundle both using some tricks involving keypaths, and overriding one would override both. I'll think about it, but this maybe not a good idea. In any case, this would be the subject of a dedicated PR.

2023-01-27 03:54 UTC, tgrapperon commented on Sources/AssertionDependency/AssertionFailure.swift
> +  /// A ``AssertionFailureAction`` that will perform an anction when reached.
```suggestion
  /// A ``AssertionFailureAction`` that will perform an action when reached.
```

2023-01-27 03:54 UTC, tgrapperon commented on Sources/AssertionDependency/AssertionFailure.swift
> +public struct AssertionFailureAction {
```suggestion
public struct AssertionFailureAction: Sendable {
```

2023-01-27 03:54 UTC, tgrapperon commented on Sources/AssertionDependency/Assert.swift
> +public struct AssertAction {
```suggestion
public struct AssertAction: Sendable {
```

2023-01-27 03:54 UTC, tgrapperon commented on Tests/AssertionDependencyTests/AssertionDependencyTests.swift
> +final class AssertionDependencyTests: XCTestCase {
`XCTExpectFailure` doesn't work on Linux, so the (implicit) convention right now is to wrap these tests in `#if os(macOS)` (at least), so they run in CI.

2023-01-27 03:54 UTC, tgrapperon commented on Package.swift
> +      name: "AssertionDependency",
We need to `@_exported import AssertDependency` in the [`Exports.swift`](https://github.com/tgrapperon/swift-dependencies-additions/blob/main/Sources/DependenciesAdditions/Exports.swift) umbrella too.

2023-01-27 12:03 UTC, tgrapperon commented
@john-flanagan, thanks for the PR! I'll cut a release in a few days.

2023-01-27 12:03 UTC, merged

2023-02-24 07:03 UTC, Sajjon commented
@john-flanagan @tgrapperon cool, I just used this, very useful! I find myself in need of a `fatalError` Dependency as well, did any of you start working on that?

Maybe this lib can act as a source of inspiration https://github.com/SlaunchaMan/ErrorAssertions ? If you haven't started I might give it a go, all tips and recommendation would be welcome ofc :)

2023-03-19 04:43 UTC, tgrapperon commented
@Sajjon Sorry, I missed your comment. 

I chose to only provide a dependency for `assert` and not for `precondition` or `fatalError` for security concerns. Users that are willing to crash should have their app crash immediately. In these case, the app is likely in an unexpected state. Providing a dependency for crashing would allow a third party to craft some values where the crash would be slightly deferred, and the breached app state logged somewhere for example.

I initially considered the same for assertions, but they are noop in `Release` mode, which is not the case of preconditions or fatal errors.

So that's why I'm a little wary of allowing such a dependency in the library for now. But feel free to open a discussion if you have use-cases or examples!